### ISSUE TITLE
Download Song Rename

### ISSUE THREAD

**Issue by iamdevl** [cachecleanerjeet/Musicder#1]
Hey, Is it possible to rename the download songs before download?

**Comment by tuhinpal** [comment]
Yes it is, if you want that you have to firstly cache that song and deliver it,

**Comment by tuhinpal** [comment]
I will add it soon. Give a ⭐

**Comment by ParveenBhadooOfficial** [comment]
> Hey, Is it possible to rename the download songs before download?

You can use netflify to proxy the Song hostname and then use HTML inbuilt `download=""` tag to rename files without using anything else.

**Comment by tuhinpal** [comment]
Thank you @ParveenBhadooOfficial  ..

**Comment by tuhinpal** [comment]
@iamdevl your requested feature have been added .

https://github.com/cachecleanerjeet/Musicder/commit/76c78c209def345cf809176a4ba1f53e09e8cfce
