### ISSUE TITLE
Download Songs with Original Names

### ISSUE THREAD

**Issue by ParveenBhadooOfficial** [cachecleanerjeet/Musicder#3]
Use Netlify to Deploy the Site,
use /dl/ something like, for cdn.saavn.com domain and then the files will be downloaded from the MUSICDER domain and you can easily use download="" tag to auto rename Songs when user downloads. download="" is only supported if the file is downloaded from same hostname.

**Comment by cachecleanerjeet** [comment]
Thanks you so much,, Means a lot that you commented, actually i used download attribute previously, but that time i didn't use a netlify proxy,, thank you so much, i will add it today,
 thanks again..

**Comment by cachecleanerjeet** [comment]
Thank you, added that :
https://github.com/cachecleanerjeet/Musicder/commit/76c78c209def345cf809176a4ba1f53e09e8cfce
