### ISSUE TITLE
Songs that includes apostrophe in the title are not downloading

### ISSUE THREAD

**Issue by shantanub08** [cachecleanerjeet/Musicder#7]
E.g. https://musicder.net/download/f6VY280u
![image](https://user-images.githubusercontent.com/39597091/105229661-49667d00-5b8a-11eb-9810-9f8415f09dd5.png)

**Comment by tuhinpal** [comment]
Nice, bug will fix it tomorrow

**Comment by tuhinpal** [comment]
Fixed Now
