### ISSUE TITLE
Can I deploy it in vps?

### ISSUE THREAD

**Issue by Naim120** [cachecleanerjeet/Musicder#8]
Can I deploy it on a vps?? If yes, then pls tell me how?

**Comment by tuhinpal** [comment]
Use Cloudflare pages

**Comment by tuhinpal** [comment]
You can deploy it on a vps too, For that build the react app and serve the output directory.

**Comment by Naim120** [comment]
Well thanks, but I ain't a developer or a computer guy. So i'll just wait, if u ever add this "Deploy on vps" feature in ur project. Thanks anyway.
